"""CueProfit Google API clients + GAQL catalog + result mappers."""

from google_clients import gaql
from google_clients.mappers import (
    CampaignDailyStat,
    ChangeEvent,
    ConversionAction,
    CustomerSnapshot,
    GeographicDailyStat,
    KeywordDailyStat,
    ProductDailyStat,
    RecommendationSnapshot,
    SearchTermDailyStat,
    map_change_event,
    map_campaign_row,
    map_conversion_action_row,
    map_customer_row,
    map_geographic_row,
    map_keyword_row,
    map_product_row,
    map_recommendation_row,
    map_search_term_row,
    row_to_flat,
)
from google_clients.merchant_mappers import MerchantCatalogProduct, map_merchant_product

__all__ = [
    "gaql",
    "CampaignDailyStat",
    "ChangeEvent",
    "ConversionAction",
    "CustomerSnapshot",
    "GeographicDailyStat",
    "KeywordDailyStat",
    "ProductDailyStat",
    "RecommendationSnapshot",
    "SearchTermDailyStat",
    "MerchantCatalogProduct",
    "map_change_event",
    "map_campaign_row",
    "map_conversion_action_row",
    "map_customer_row",
    "map_geographic_row",
    "map_keyword_row",
    "map_product_row",
    "map_recommendation_row",
    "map_search_term_row",
    "map_merchant_product",
    "row_to_flat",
]
